### ISSUE TITLE
fetching large amount of data

### ISSUE THREAD

**Issue by den1zk** [twitter/pelikan#118]
Hi,
I used twemcache for caching large amount of data(consisting of approximately 111000 characters), however I cannot fetch more than 80000 characters when I try to get the value back.

**Comment by kevyang** [comment]
Hi @den1zk, could you provide some more details or tell us how to reproduce your bug? One of our team members ran the following locally and got all 111000 characters:

`$ perl -e 'print "set foo 0 0 111000\r\n", "1"x111000, "\r\n"' | nc -C localhost 12321`
`STORED `
`$ perl -e 'print "get foo\r\n"' | nc -C localhost 12321 | wc -c `
`111027`

**Comment by den1zk** [comment]
hi,
I was using the following library for Node.js => https://github.com/3rd-Eden/memcached.
My key was "agent_asset/agent:IYM"  and the value was a large JSON string consisting of 111398 characters.
ps: I tried many other libraries after failing to get whole data from the first one and in the end concluded that the problem was not the library.

**Comment by den1zk** [comment]
hi,
I forgot to say that I tried to get data using telnet, too. The response was incomplete just like the previous case.

**Comment by kevyang** [comment]
Can you confirm that your JSON contains no CRLF (in other words, "\r\n")?

**Comment by kevyang** [comment]
Closing this issue, please reopen if you can provide more details
