### ISSUE TITLE
flaky test in travis?

### ISSUE THREAD

**Issue by thinkingfish** [twitter/pelikan#135]
```sh
$ cd ../test && python -m unittest discover

F

======================================================================

FAIL: test_miss (integration.test_twemcache_basic.TwemcacheBasicTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/twitter/pelikan/test/integration/test_twemcache_basic.py", line 7, in test_miss

    self.assertMetrics(('request_parse', 1), ('get', 1), ('get_key_miss', 1))

  File "/home/travis/build/twitter/pelikan/test/integration/base.py", line 40, in assertMetrics

    stats.get(k, None),

AssertionError: Expected request_parse to be 1, got 0 instead

----------------------------------------------------------------------

Ran 1 test in 0.005s

FAILED (failures=1)

The command "cd ../test && python -m unittest discover" exited with 1.

Done. Your build exited with 1.
```

This occurred for all tests last night, went away this morning, and has now returned.

**Comment by thinkingfish** [comment]
@seppo0010 This was what made me take out the integration tests earlier.

**Comment by seppo0010** [comment]
Oh, wow, that's surprising... The test successfully read "END" but metrics are still 0... may that be an actual bug in pelikan?

**Comment by thinkingfish** [comment]
But other times it succeeded (on travis), and it always runs fine locally.

**Comment by thinkingfish** [comment]
The same behavior returned on travis. I'm disabling integration test until I can figure out why.

**Comment by thinkingfish** [comment]
I have merged the partial value change because I have two other branches that depend on it, including more tests. Will prioritize getting those tests in.

**Comment by seppo0010** [comment]
I'm now surprised this actually worked certain times... see #139.

**Comment by thinkingfish** [comment]
Indeed. Curious.

But we should re-enable the test now that you fixed the bug :)

**Comment by seppo0010** [comment]
The test was reenabled in that PR. Close this issue, please (I cannot!).
