### ISSUE TITLE
Benchmark for twemcache/pelikan_twemcache

### ISSUE THREAD

**Issue by QingchenDang** [twitter/pelikan#329]
Hi,

I wonder is there any benchmark to test twemcache or pelikan_twemcache? Or is it possible to configure Memcached's benchmarks such as Memtier_benchmark or Memaslap to be compatible with twemcache/pelikan_twemcache as well?

Thanks,
Qingchen

**Comment by 1a1a11a** [comment]
You can take a look at RPC-perf (https://github.com/twitter/rpc-perf), pelikan_twemcache supports Memcached protocol, you can also use other benchmarks like Memtier_benchmark

**Comment by QingchenDang** [comment]
Thank you for your response! For RPC-perf, should the protocol be set to 'memcache' to run on pelikan_twemcache?

Furthermore, I encountered an issue for running pelican_twemcache. It failed to start, but it does not produce any errors. I run it on Ubuntu as following:

**qingchend@fat2:~/pelikan/_build$ _bin/pelikan_twemcache ../config/twemcache.conf
load config from ../config/twemcache.conf
set up the ccommon::log module
Set up the ccommon::debug module
create logger with filename twemcache.log cap 1048576
create logger with filename twemcache.cmd cap 2097152
Tear down the ccommon::debug module
tear down the ccommon::log module
qingchend@fat2:~/pelikan/_build$**

I re-run the the tests, and it gets struck on test 28. After showing "Start 28: integration", it never finishes running. I did not find any related issues from others. Could you take a look?
