### ISSUE TITLE
[portability] compile error on non-x86

### ISSUE THREAD

**Issue by varkappadev** [twitter/pelikan#394]
**Describe the bug**
`src/storage/seg/hashtable.c` unconditionally includes `x86intrin.h` and thus fails to compile on non-x86

**To Reproduce**
compile as per build instructions, `make -j` fails

**Expected behavior**
builds successfully 

**Environment**
macOS 12.1 (arm64, i.e. M1) with Homebrew clang version 13.0.0

**Additional context**
feel free to close (but please update the requirements in README.md) if pelikan is only intended for x86_64

Thanks!

**Comment by 1a1a11a** [comment]
we will remove the include because it is not needed, thank you for pointing out

**Comment by thinkingfish** [comment]
Please reopen if other things are in the way.
