### ISSUE TITLE
rust: storage/seg - implement an iterator for item info

### ISSUE THREAD

**Issue by brayniac** [twitter/pelikan#414]
In the hashtable module, we are frequently iterating through the hash buckets and info slots to get item info. This is a lot of duplicate code that feels like it can be more concisely expressed at the call sites as an iterator.

**Comment by hderms** [comment]
@brayniac are you referring to iterations like this repeated chunk: 

https://github.com/twitter/pelikan/blob/13b1b3ac1fd3f6181bee790e64133fbd125842b3/src/rust/storage/seg/src/hashtable/mod.rs#L307-L318

**Comment by brayniac** [comment]
@hderms - yes. It feels like we can provide an iterator where the iterator's item type is ItemInfo which would be a new type
