### ISSUE TITLE
Switch inclusion of header files from <> to ""

### ISSUE THREAD

**Issue by kevyang** [twitter/pelikan#95]

**Comment by elfring** [comment]
Would you like to [reconsider this proposal](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by thinkingfish** [comment]
@elfring Can you elaborate? 

To clarify: We currently almost use always use `<>`, this issue is suggesting using `""` for all the headers local within the pelikan repo (i.e. excluding deps – `ccommon` and systems headers)

**Comment by elfring** [comment]
Do the include statements which are using angle brackets so far refer to header files that belong to application programming interfaces?

**Comment by thinkingfish** [comment]
@elfring Yes. We basically _were_ using angle brackets for _everything_.

**Comment by elfring** [comment]
Is [the use of angle brackets](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?") more appropriate occasionally?

**Comment by thinkingfish** [comment]
@elfring I'm not exactly sure what the best practice is. I've seen people using angle brackets *only* for system libraries, and I've seen the other extreme where angle brackets are used liberally (twemcache, twemproxy actually fell into the latter camp).

For now, we have restricted angle brackets to be used for anything that's *not* under `pelikan/src`, including `ccommon` includes, which seems to a little more liberal than average. This is mostly to make local includes – such as having the `.c` include the corresponding `.h` – as concise as possible.

If anybody knows more feel free to comment.
